#!/bin/bash

set -u
set -e

CURRENT_DIR=$( /bin/pwd )

mkdir -m 0775 -p Libraries

touch ../airbitz-core/deps/recipes/abc/abc.recipe

if [ "${1-}" = "testnet" ]; then
    shift
    (
        cd ../airbitz-core/deps
        export BUILD_DIR=${CURRENT_DIR}/../airbitz-core/deps/build-testnet
        make abc.package-ios-universal ENABLE_TESTNET=1 $@
    )
    cp -aL ../airbitz-core/deps/build-testnet/abc/abc-ios-universal/include/* Classes/Private 
    cp -a ../airbitz-core/deps/build-testnet/abc/abc-ios-universal/lib/* Libraries/
else
    (
        cd ../airbitz-core/deps
        export BUILD_DIR=${CURRENT_DIR}/../airbitz-core/deps/build
        make abc.package-ios-universal $@
    )
    cp -aL ../airbitz-core/deps/build/abc/abc-ios-universal/include/* Classes/Private
    cp -a ../airbitz-core/deps/build/abc/abc-ios-universal/lib/* Libraries/
fi
