#!/bin/bash
set -u
set -e

# Pick up the current directory:
CURRENT_DIR=$(pwd)
if [ -z ${BUILD_DIR+x} ]; then
  export BUILD_DIR=${BUILD_DIR:-$CURRENT_DIR/../airbitz-core/deps/build};
fi

# Testnet options:
if [ "${1-}" = "testnet" ]; then
    shift
    export BUILD_DIR=${BUILD_DIR}-testnet
    export ENABLE_TESTNET=1
fi

# Do the build:
touch ../airbitz-core/deps/recipes/abc/abc.recipe
(
    cd ../airbitz-core/deps
    make abc.package-ios-universal $@
)

# Copy the results locally:
mkdir -m 0775 -p Libraries
cp -aL $BUILD_DIR/abc/abc-ios-universal/include/* Classes/Private
cp -a $BUILD_DIR/abc/abc-ios-universal/lib/* Libraries/
