#!/bin/bash

set -u
set -e

CURRENT_DIR=$( /bin/pwd )


appledoc --index-desc main-help.m --project-name airbitz-core-objc --project-company "Airbitz" --company-id co.airbitz --output ./help --no-create-docset --search-undocumented-doc Classes/Public/.

